server:
  port: 8081


spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: girocloud
  jpa:
    show-sql: false
    defer-datasource-initialization: true
  h2:
    console.enabled: true
