server:
  port: 8081


spring:
  thymeleaf:
    cache: false
#  datasource:
#    generate-unique-name: false
#    name: girocloud
#    url: jdbc:h2:mem:girocloud;DB_CLOSE_ON_EXIT=FALSE
#  jpa:
#    show-sql: false
#  h2:
#    console.enabled: true
  data:
    cassandra:
      keyspace-name: giro_cloud
      schema-action: recreate
      local-datacenter: datacenter1